Repository yourssu-rookies/unscramble-android-1, pull requests merged in 2024-01, with the labels that each got.

#3 [Setting] PR 템플릿
  .github/pull_request_template.md
Labels: docs

#4 [Update] README.md
  README.md
Labels: docs

#2 [feat/initial_settings] initial setting
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yourssu/unscramble/MyApplication.kt
  app/src/main/java/com/yourssu/unscramble/presentation/ExampleFragment.kt
  app/src/main/java/com/yourssu/unscramble/presentation/MainActivity.kt
  app/src/main/java/com/yourssu/unscramble/presentation/viewmodel/ActivityViewModel.kt
  app/src/main/java/com/yourssu/unscramble/ui/ComposeActivity.kt
  app/src/main/java/com/yourssu/unscramble/util/base/BindActivity.kt
  app/src/main/java/com/yourssu/unscramble/util/base/BindFragment.kt
  app/src/main/java/com/yourssu/unscramble/util/extension/ContextExtension.kt
  app/src/main/java/com/yourssu/unscramble/util/extension/IntentExtension.kt
  app/src/main/java/com/yourssu/unscramble/util/extension/StringExtension.kt
  app/src/main/java/com/yourssu/unscramble/util/extension/ViewExtension.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_example.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  settings.gradle.kts
Labels: add

#10 [Feat] 프레그먼트 및 네비게이션 세팅
  README.md
  app/build.gradle.kts
  app/src/main/java/com/yourssu/unscramble/presentation/EndFragment.kt
  app/src/main/java/com/yourssu/unscramble/presentation/MainActivity.kt
  app/src/main/java/com/yourssu/unscramble/presentation/PlayFragment.kt
  app/src/main/java/com/yourssu/unscramble/presentation/StartFragment.kt
  app/src/main/java/com/yourssu/unscramble/presentation/TimerFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_end.xml
  app/src/main/res/layout/fragment_example.xml
  app/src/main/res/layout/fragment_play.xml
  app/src/main/res/layout/fragment_start.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat
